"""phase2 api_keys table

Revision ID: 2dcb5d78d48e
Revises: c7b2fa449db2
Create Date: 2026-06-01 11:08:52.493173

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcb5d78d48e'
down_revision: str | None = 'c7b2fa449db2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    # NOTE: autogenerate also wanted to drop carbon_intensity_hourly_period_idx
    # and generation_hourly_period_idx — those are TimescaleDB's internal
    # hypertable indexes, not app indexes. Leaving them in place.


def downgrade() -> None:
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
