"""phase1 reference and timeseries tables

Revision ID: c7b2fa449db2
Revises: 20b77484f410
Create Date: 2026-06-01 10:49:31.524469

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b2fa449db2'
down_revision: str | None = '20b77484f410'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_code', sa.String(length=8), nullable=False),
    sa.Column('fuel_name', sa.String(length=64), nullable=False),
    sa.Column('co2_lb_per_mwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_renewable', sa.Boolean(), nullable=False),
    sa.Column('is_carbon_free', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.CheckConstraint("confidence IN ('high','low')", name='ck_factor_confidence'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_code', 'version', name='uq_emission_fuel_version')
    )
    op.create_table('regions',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('egrid_subregion', sa.String(length=8), nullable=True),
    sa.Column('mapping_confidence', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.CheckConstraint("mapping_confidence IN ('exact', 'dominant', 'approximate')", name='ck_region_confidence'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('carbon_intensity_hourly',
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gco2_per_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_mwh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('renewable_share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('carbon_free_share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('low_confidence_share', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('region_code', 'period')
    )
    op.create_table('generation_hourly',
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuel_code', sa.String(length=8), nullable=False),
    sa.Column('mwh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('region_code', 'period', 'fuel_code')
    )
    op.create_table('zip_region',
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('mapping_confidence', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.CheckConstraint("mapping_confidence IN ('exact', 'dominant', 'approximate')", name='ck_zip_confidence'),
    sa.ForeignKeyConstraint(['region_code'], ['regions.code'], ),
    sa.PrimaryKeyConstraint('zip')
    )
    # ### end Alembic commands ###

    # Convert the time-series tables to TimescaleDB hypertables (partitioned on
    # `period`). Their PKs include `period`, satisfying Timescale's unique-index
    # requirement.
    op.execute(
        "SELECT create_hypertable('generation_hourly', 'period', "
        "chunk_time_interval => INTERVAL '7 days')"
    )
    op.execute(
        "SELECT create_hypertable('carbon_intensity_hourly', 'period', "
        "chunk_time_interval => INTERVAL '7 days')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_region')
    op.drop_table('generation_hourly')
    op.drop_table('carbon_intensity_hourly')
    op.drop_table('regions')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
